;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        bryan-multiple-cursors-hydra/mc/edit-lines-and-exit
        bryan-multiple-cursors-hydra/mc/mark-all-like-this-and-exit
        bryan-multiple-cursors-hydra/mc/mark-previous-like-this
        bryan-multiple-cursors-hydra/mc/skip-to-next-like-this
        bryan-multiple-cursors-hydra/mc/unmark-previous-like-this
        evil-append
        evil-append-line
        evil-backward-WORD-begin
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-delete-line
        evil-digit-argument-or-evil-beginning-of-line
        evil-emacs-state
        evil-end-of-line
        evil-first-non-blank
        evil-force-normal-state
        evil-forward-WORD-begin
        evil-forward-WORD-end
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        evil-inner-tag
        evil-insert
        evil-insert-line
        evil-insert-resume
        evil-next-line
        evil-normal-state
        evil-paredit-yank
        evil-previous-line
        evil-set-marker
        keyboard-quit
        paredit-backward-barf-sexp
        paredit-backward-slurp-sexp
        paredit-doublequote
        paredit-forward-barf-sexp
        paredit-forward-slurp-sexp
        paredit-open-round
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        bryan-multiple-cursors-hydra/mc/mark-next-like-this
        evil-scroll-page-up
        evil-search-forward
        evil-search-next
        helm-mini
        isearch-exit
        magit-status
        ))
