;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append-line
        evil-backward-WORD-begin
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete
        evil-delete-char
        evil-delete-line
        evil-digit-argument-or-evil-beginning-of-line
        evil-emacs-state
        evil-end-of-line
        evil-first-non-blank
        evil-force-normal-state
        evil-forward-WORD-begin
        evil-forward-WORD-end
        evil-forward-char
        evil-forward-word-begin
        evil-forward-word-end
        evil-insert
        evil-next-line
        evil-normal-state
        evil-previous-line
        keyboard-quit
        paredit-backward-barf-sexp
        paredit-backward-slurp-sexp
        paredit-forward-barf-sexp
        paredit-forward-slurp-sexp
        paredit-open-round
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        evil-scroll-page-up
        evil-search-forward
        helm-mini
        isearch-exit
        magit-status
        ))
