#+title: .emacs.d

Read about switching from Vim to Emacs in my blog post, [[http://www.bryangarza.me/my-descent-into-evil.html][My Descent Into Evil]].

* Table of Contents                                                :TOC_2_gh:
 - [[#important][Important!]]
     - [[#paredit][Paredit]]
     - [[#org-mode][Org mode]]
     - [[#org-present][Org-present]]
     - [[#hydras][Hydras]]
     - [[#zooming][Zooming]]
     - [[#unbinding][Unbinding]]
     - [[#pinning][Pinning]]
     - [[#helm][Helm]]
     - [[#circe][Circe]]
     - [[#aligning-code][Aligning Code]]
     - [[#editing-with-sudo][Editing with Sudo]]
     - [[#keybindings][Keybindings]]
     - [[#updating-submodules][Updating submodules]]
     - [[#finding-face-under-point][Finding face under point]]
 - [[#here-be-dragons][Here Be Dragons]]
 - [[#when-cloning][When Cloning]]
     - [[#ocaml][OCaml]]
     - [[#irc][IRC]]
     - [[#submodules][Submodules]]
 - [[#graphical-vs-console-emacs][Graphical vs Console Emacs]]
 - [[#languages][Languages]]
 - [[#packages-and-modes][Packages and Modes]]
 - [[#license][License]]
 - [[#internal-notes][Internal Notes]]

* Important!

** Paredit

- [[http://www.emacswiki.org/emacs/PareditCheatsheet][Paredit Cheatsheet]]
- [[http://mumble.net/~campbell/emacs/paredit.html][Another Paredit Cheatsheet]]

** Org mode

- [[http://orgmode.org/org.html][The Org Manual]]
- [[http://orgmode.org/guide/][The compact Org-mode Guide]]
- [[https://emacsclub.github.io/html/org_tutorial.html][Org-mode Tutorial / Cheat Sheet]]

** Org-present

- left and right for movement
- =C-c C-== for large text
- =C-c C--= for small text
- =C-c C-q= to quit (which will return you back to vanilla org-mode)
- =C-c <= to jump to first slide
- =C-c >= to jump to last slide

** Hydras

- =C-c m= Hydra for all hydras
- =C-c w= Window movement and manipulation
- =C-c c= Multiple cursors
- =C-c o= Org mode headings
- =C-c a= Avy

** Zooming

- =C-x C-+= and =C-x C--= (‘text-scale-adjust’) to increase or
  decrease the buffer text size
- =C-+= or =C--= to repeat
- =C-x C-0= to restore the default (global) face height
- =S-mouse-1= pops up a menu where you can choose these same actions

** Unbinding

This will make the symbol my-nasty-variable's value void:

#+BEGIN_SRC emacs-lisp
(makunbound 'my-nasty-variable)
#+END_SRC

This will make the symbol my-nasty-function's function definition void:

#+BEGIN_SRC emacs-lisp
(fmakunbound 'my-nasty-function)
#+END_SRC

** Pinning

If I ever want to pin packages:

#+BEGIN_SRC emacs-lisp
(setq 'package-archives '(("melpa"        . "http://melpa.org/packages/")
                          ("melpa-stable" . "http://stable.melpa.org/packages/")))

(use-package company
  :ensure t
  :pin melpa-stable)
#+END_SRC

** Helm

- [[http://emacs-helm.github.io/helm/][Helm home page]]
- [[http://tuhdo.github.io/helm-intro.html][Helm intro]]

** Circe

- [[https://github.com/howardabrams/dot-files/blob/master/emacs-irc.org][Howard Abrams' IRC settings]]
- [[https://github.com/jorgenschaefer/circe/wiki/Configuration][Circe wiki: Configuration]]

** Aligning Code

[[https://wiki.haskell.org/Emacs/Indentation#Aligning_code][Haskell wiki: aligning code in Emacs]]

#+BEGIN_SRC emacs-lisp
(bind-key "C-x a r" 'align-regexp)
#+END_SRC

** Editing with Sudo

#+BEGIN_EXAMPLE
C-x C-f /sudo::/path/to/file
#+END_EXAMPLE

** Keybindings

Most of the keybindings I have set can be found in
=bryan/bryan-keybindings.el=. The majority involve the Super key,
which on Mac is the Command key. On Windows or GNU/Linux, this is
probably your Win key, but if it's not bound, then just bind it!

** Updating submodules

#+BEGIN_SRC sh
git submodule foreach git pull origin master
#+END_SRC

** Finding face under point

~what-cursor-position~ with a prefix argument shows the face under point, among other information.

Keyboard shortcut is =C-u C-x ==.

* Here Be Dragons

This setup is heavily customized, [[http://www.bryangarza.me/contact.html][let me know]] if you run into any problems and
we can troubleshoot. Though official support is neither offered nor guaranteed,
I'd like this configuration to be useful to others.

* When Cloning

** OCaml

OCaml settings require external installation, see
[[https://github.com/realworldocaml/book/wiki/Installation-Instructions][Real World OCaml's GitHub wiki]]. If you don't care about OCaml, simply comment
out =bryan-ocaml= in =bryan-pkg-full=.

** IRC

Create a file =~/.private.el=:

#+BEGIN_SRC emacs-lisp
(setq freenode-password "YOUR_PASSWORD")
      freenode-username "YOUR_USERNAME")
#+END_SRC

You can use ~M-x circe~, though lately it has been acting strangely; sometimes
the window management is broken by circe and then only way I've been able to fix
it is by restarting Emacs. The simpler alternative is ~M-x rcirc~, though I have
not yet figured out how to get it to identify to Nickserv automatically
yet. Circe does have automatic identify working.

** Submodules

Remember to also clone *submodules*:

#+BEGIN_SRC sh
git clone --recursive git@github.com:bryangarza/dot-emacs.git
#+END_SRC

* Graphical vs Console Emacs

This setup will work much better with *Graphical* Emacs than the terminal-based
Emacs. This is because the terminal gobbles up various key chords. Not to
mention graphical Emacs has mouse support, can display multiple font sizes, and
PDFs, and images.

See my Medium post (linked above) for Cocoa Emacs installation instructions with
=homebrew=. If you're on GNU/Linux, just install the =emacs= package, that
should come with both the graphical and terminal emacs.

In case you're curious, use ~emacs -nw~ to run in console mode. I haven't found
this config to work well with console mode though, especially because iTerm 2
takes control of the ⌘ key, as well as some other chords. Your experience may
vary.

* Languages

I've configured it for the following languages:
- HTML
- CSS
- JavaScript
- Markdown
- Elisp
- Clojure
- Haskell
- OCaml
- C
- Jade
- Stylus
- Scheme
- Racket
- Scala
- Hy
- LaTeX
- Rust
- Elm

Other languages may work out-of-the-box, for example I have not changed any
settings for Python but the default editing experience is decent as-is.

* Packages and Modes

Notable packages and modes that I use include

- Evil
- Paredit
- Helm, Helm Swoop
- Flycheck
- Multiple Cursors
- Ace Jump

* License

Copyright (C) 2015 Bryan Garza

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, either version 3 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program.  If not, see <http://www.gnu.org/licenses/>.

* Internal Notes

Because I keep forgetting the Org mode formatting:

#+BEGIN_EXAMPLE
You can make words *bold*, /italic/, _underlined_, =verbatim= and ~code~, and,
if you must, ‘+strike-through+’. Text in the code and verbatim string is not
processed for Org mode specific syntax, it is exported verbatim.
#+END_EXAMPLE

Batch resizing images on the command line:
#+BEGIN_SRC shell
sips -Z 640 *.jpg
#+END_SRC
