#+title: .emacs.d

Read about switching from Vim to Emacs in my Medium post, [[https://medium.com/@bryangarza/my-descent-into-evil-98f7017475b6][My Descent Into Evil]].

** Here Be Dragons

This setup is heavily customized, [[http://www.bryangarza.me/contact.html][let me know]] if you run into any problems and
we can troubleshoot.

** When Cloning

OCaml settings require external installation, see
[[https://github.com/realworldocaml/book/wiki/Installation-Instructions][Real World OCaml's GitHub wiki]]. If you don't care about OCaml, simply comment
out that section of the config.

For IRC, change the username in =init.el=, and create a file =~/.private.el=:

#+BEGIN_SRC emacs-lisp
(setq freenode-password "YOUR_PASSWORD")
#+END_SRC

Remember to also clone *submodules*:

#+BEGIN_SRC shell
git clone --recursive git@github.com:bryangarza/dot-emacs.git
#+END_SRC

This setup will work much better with *Cocoa* Emacs than terminal Emacs. This is
because the terminal gobbles up various key chords. Not to mention graphical
Emacs has mouse support, and can display PDFs and images.

See my Medium post (linked above) for Cocoa Emacs installation instructions with
=homebrew=.

** Languages

I've configured it for the following languages:
- HTML
- CSS
- JavaScript
- Markdown
- Elisp
- Clojure
- Haskell
- OCaml
- C
- Jade
- Stylus
- Scheme
- Racket
- Scala
- Hy
- LaTeX

Other languages may work out-of-the-box, for example I have not changed any
settings for Python but the default editing experience is decent as-is.

** Packages and Modes

Notable packages and modes that I use include

- Evil
- Paredit
- Helm, Helm Swoop
- Flycheck
- Multiple Cursors
- Ace Jump
